apiVersion: v1
kind: Service

metadata:
  name: devops-service
  namespace: devops-pipeline

spec:
  type: NodePort

  selector:
    app: devops-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
